name: Build ZMK Firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build firmware
        uses: zmkfirmware/zmk-build-firmware@main
        with:
          config_path: config

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: touchpad-firmware
          path: build/artifacts/*.uf2
